baseURL = "https://willj.net/"
languageCode = "en-gb"
title = "Will Jessop's writings"

[author]
    name = "Will Jessop"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "edit"
    url = "/posts/"
    weight = 2
 # [[menu.main]]
 #   name = "Tags"
 #   pre = "tag"
 #   url = "/tags/"
 #   weight = 3
