baseURL = "https://willj.net/"
languageCode = "en"
title = "Will Jessop's Writings"
rssLimit = 20
copyright = "&#169; Will Jessop. All rights reserved."
enableRobotsTXT = true

[Params]
  OpenToContracts = true

[author]
    name = "Will Jessop"
    email = "will@willj.net"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "edit"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    baseName = "rss"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
